---
- name: win_chocolatey module demo
  hosts: 107.21.75.6
  become: false
  gather_facts: false
  vars:
    - packages:
      - git
      - notepadplusplus
 tasks:
- name: install packages
  win_chocolatey:
    name: "{{ packages }}"
    state: present
