---
- name: win_chocolatey module demo
  hosts: 107.21.75.6
  become: false
  gather_facts: false
  tasks:
  
- name: Install git
  win_chocolatey:
    name: git
    state: present
    
- name: Install notepadplusplus version 6.6
  win_chocolatey:
    name: notepadplusplus
    version: '6.6'
    
- name: Install multiple packages sequentially
  win_chocolatey:
    name: '{{ item }}'
    state: present
  loop:
  - procexp
  - putty
  - windirstat
    
